In [2]:
import pandas as pd
df = pd.read_csv("titanic.csv") 
df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
print(df.isnull().sum())

Unnamed: 0       0
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
age_median = df['age'].median()
df['age'].fillna(age_median, inplace=True)

town_mode = df['embark_town'].mode()[0]
df['embark_town'].fillna(town_mode, inplace=True)

deck_mode = df['deck'].mode()[0]
df['deck'].fillna(deck_mode, inplace=True)

print(df.isnull().sum())

Unnamed: 0       0
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

/var/folders/fy/fymgqtx565j7bql0f3smqp900000gn/T/ipykernel_21495/621027403.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'].fillna(age_median, inplace=True)
/var/folders/fy/fymgqtx565j7bql0f3smqp900000gn/T/ipykernel_21495/621027403.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['embark_town'].fillna(town_mode, inplace=True)
/var/folders/fy/fymgqtx565j7bql0f3smqp900000gn/T/ipykernel_21495/621027403.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['deck'].fillna(deck_mode, inplace=True)

In [5]:
age_median = df['age'].median()
df['age'] = df['age'].fillna(age_median)

town_mode = df['embark_town'].mode()[0]
df['embark_town'] = df['embark_town'].fillna(town_mode)

deck_mode = df['deck'].mode()[0]
df['deck'] = df['deck'].fillna(deck_mode)

print(df.isnull().sum())

Unnamed: 0     0
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [6]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['age', 'fare']] = scaler.fit_transform(df[['age', 'fare']])

df.head()

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,0.271174,1,0,0.014151,S,Third,man,True,C,Southampton,no,False
1,1,1,1,female,0.472229,1,0,0.139136,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,0.321438,0,0,0.015469,S,Third,woman,False,C,Southampton,yes,True
3,3,1,1,female,0.434531,1,0,0.103644,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,0.434531,0,0,0.015713,S,Third,man,True,C,Southampton,no,True

In [8]:
cols_to_fix = ['sex', 'embark_town', 'who']

df = pd.get_dummies(df, columns=cols_to_fix, drop_first=True)

if 'alive' in df.columns:
    df.drop('alive', axis=1, inplace=True)

df.head()

,Unnamed: 0,survived,pclass,age,sibsp,parch,fare,embarked,class,adult_male,deck,alone,sex_male,embark_town_Queenstown,embark_town_Southampton,who_man,who_woman
0,0,0,3,0.271174,1,0,0.014151,S,Third,True,C,False,True,False,True,True,False
1,1,1,1,0.472229,1,0,0.139136,C,First,False,C,False,False,False,False,False,True
2,2,1,3,0.321438,0,0,0.015469,S,Third,False,C,True,False,False,True,False,True
3,3,1,1,0.434531,1,0,0.103644,S,First,False,C,False,False,False,True,False,True
4,4,0,3,0.434531,0,0,0.015713,S,Third,True,C,True,True,False,True,True,False